server:
  port: 8088
  tomcat:
    uri-encoding: UTF-8
    max-http-post-size: 80KB

############################################################
# 配置数据源信息#
############################################################
#spring:
#  datasource:	                                #  数据源的相关配置
#     type:  com.zaxxer.hikari.HikariDataSource	#  数据源类型：HikariCP
#     driver-class-name:  com.mysql.cj.jdbc.Driver	#  mysql驱动
#     url:  jdbc:mysql://localhost:3306/foodie-shop-dev?useUnicode=true&characterEncoding=UTF-8&autoReconnect
#     username:  root
#     password:  hwd0221
#     hikari:
#       connection-timeout:  30000	#  等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQ minimum-idle:  5	#  最小连接数
#       maximum-pool-size:  20	#  最大连接数
#       auto-commit:  true	#  自动提交
#       idle-timeout:  600000	#  连接超时的最大时长（毫秒），超时则被释放（retired），默认:10分钟
#       pool-name:  DateSourceHikariCP		#  连接池名字
#       max-lifetime:  1800000	#  连接的生命时长（毫秒），超时而且没被使用则被释放（retired），默认:30分钟
#       connection-test-query:  SELECT  1


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/foodie-shop?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: hwd0221
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 600000
      pool-name: DateSourceHikariCP
      max-lifetime: 1800000
      connection-test-query: SELECT  1
      minimum-idle: 5
############################################################  #
#  mybatis  配置 #
############################################################
mybatis:
  type-aliases-package:  com.yubo.pojo	#  所有POJO类所在包路径
  mapper-locations:  classpath:mapper/*.xml	#  mapper映射文件
  configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#通用mapper设置
mapper:
  identity: MYSQL
  mappers: com.yubo.my.mapper.MyMapper
  not-empty: false #在进行数据库操作的时候，判断username != null  判断帮我们自动追加username!=''
