server:
  port: 8088

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://110.40.137.196:3306/mall?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: hwd0221
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 600000
      pool-name: DateSourceHikariCP
      max-lifetime: 1800000
      connection-test-query: SELECT  1
      minimum-idle: 5
  redis:
    database: 1
    host: 110.40.137.196
    port: 6379
    timeout: 5000
    password: hwd0221
